### ISSUE TITLE
Include path not working

### ISSUE THREAD

**Issue by jsyathon** [qd-cae/qd-cae-python#53] opened 2019-04-17 21:39 UTC
Hi,

I'm trying to parse a file with some includes, but for some reason qd doesn't seem to be picking up the `*INCLUDE_PATH` keyword properly.  

See attached zip file for a small example.  This runs properly in LS-DYNA, but when I try to load the keyfile `test_1.k` I get the following error: `ValueError: Can not find: db_files.k`

Thanks!
[mainfolder.zip](https://github.com/qd-cae/qd-cae-python/files/3091643/mainfolder.zip)

**Comment by lasso-codie** [comment] 2019-04-18 10:05
Hi,
thanks for reporting, I can reproduce it. Should be fixed quickly ... hopefully.

**Comment by lasso-codie** [comment] 2019-04-18 12:06
The issue is, that the include path of the parent file is not used in the child include. Can you confirm that LS-Dyna uses the parent include path also in child includes?

**Comment by jsyathon** [comment] 2019-04-18 15:56
Yes I can confirm that LS-DYNA is able to parse the file structure I attached.  I also tested a situation where an additional `*INCLUDE_PATH` is provided in the child include, it works in LS-DYNA.  See attached (again, target file is `test_1.k`).
[test_1_includes.zip](https://github.com/qd-cae/qd-cae-python/files/3095192/test_1_includes.zip)

**Comment by lasso-codie** [comment] 2019-04-18 16:15
Ah wait just tested it again, what are you exactly running to get the error?

I ran:
```python
>>> kf = KeyFile("test_1.k", load_includes=True)
>>> kf.get_includes()
[<qd.cae.dyna_cpp.QD_KeyFile object at 0x0000022C07830DC0>]
>>> len(kf.get_includes()[0].get_includes())
2
```

So it seems as if it is loading the includes correctly. Note that the child includes are not loaded into the parent. I wanted to prevent people making changes to keywords in some include below and forget saving it afterwards.

**Comment by jsyathon** [comment] 2019-04-18 18:36
Some further testing reveals that the error occurs when my current directory is not the same as that of the parent keyfile (regardless of whether full or relative paths are provided).  I am on Windows 7 for reference.  Full history here:

```
C:\Work_files\LSDYNA test\test_1_includes>python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qd.cae.dyna import *
>>> kf = KeyFile('mainfolder/test_1.k', load_includes=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Can not find: db_files.k
>>> exit()

C:\Work_files\LSDYNA test\test_1_includes>cd mainfolder

C:\Work_files\LSDYNA test\test_1_includes\mainfolder>python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qd.cae.dyna import *
>>> kf = KeyFile('test_1.k', load_includes=True)
>>> len(kf.get_includes()[0].get_includes())
2
```

As a separate issue, I get an error when I try to parse the second keyfile structure (https://github.com/qd-cae/qd-cae-python/issues/53#issuecomment-484571648), even if I am in the same directory as the parent keyfile.

**Comment by lasso-codie** [comment] 2019-04-19 11:18
Okay fixed the first issue. The second is still to go.

**Comment by lasso-codie** [comment] 2019-04-25 22:39
still couldn't fix it. Hadn't one like that in a while.

**Comment by lasso-codie** [comment] 2019-04-26 14:50
Okay got it, the issue in the code was as I stated that the relative path of the include in level 1 was resolved also with the base dir of the level 1 include. As you stated though, the master keyfile dir is used as basis for any other lower level include. 

e.g.
 - some/dir/master.key
   > INCLUDE_PATH: subdir
   > INCLUDE: child.key
 - some/dir/subdir/child.key
   > INCLUDE_PATH: ../super_dir/another/dir
   > INCLUDE: child2.key
- some/dir/../super_dir/another/dir/child2.key
   > ...

Note the difference:
 - (old) `some/dir/subdir/../super_dir/another/dir/child2.key`
 - (new) `some/dir/../super_dir/another/dir/child2.key`

At least with this fix it works now. If you agree that this is correct, I will issue a release fix 0.8.8 these days.

**Comment by jsyathon** [comment] 2019-04-26 21:12
Yes that looks correct to me.

Thanks for the fix, I'm trying to deal with fairly complicated models and this should help a lot.

**Comment by lasso-codie** [comment] 2019-04-27 09:47
It is now available on pip

**Closed by lasso-codie** 2019-04-27 09:47 UTC
Labels: bug
